# Generated by Django 4.2.1 on 2023-05-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WeatherData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("epoch", models.IntegerField()),
                ("humidityAvg", models.FloatField()),
                ("humidityHigh", models.FloatField()),
                ("humidityLow", models.FloatField()),
                ("lat", models.FloatField()),
                ("lon", models.FloatField()),
                ("obsTimeLocal", models.DateTimeField()),
                ("obsTimeUtc", models.DateTimeField()),
                ("solarRadiationHigh", models.FloatField()),
                ("stationID", models.CharField(max_length=255)),
                ("tz", models.CharField(max_length=255)),
                ("uvHigh", models.FloatField()),
                ("winddirAvg", models.FloatField()),
                ("dewptAvg", models.FloatField()),
                ("dewptHigh", models.FloatField()),
                ("dewptLow", models.FloatField()),
                ("heatindexAvg", models.FloatField()),
                ("heatindexHigh", models.FloatField()),
                ("heatindexLow", models.FloatField()),
                ("precipRate", models.FloatField()),
                ("precipTotal", models.FloatField()),
                ("pressureMax", models.FloatField()),
                ("pressureMin", models.FloatField()),
                ("pressureTrend", models.FloatField()),
                ("qcStatus", models.IntegerField()),
                ("tempAvg", models.FloatField()),
                ("tempHigh", models.FloatField()),
                ("tempLow", models.FloatField()),
                ("windchillAvg", models.FloatField()),
                ("windchillHigh", models.FloatField()),
                ("windchillLow", models.FloatField()),
                ("windgustAvg", models.FloatField()),
                ("windgustHigh", models.FloatField()),
                ("windgustLow", models.FloatField()),
                ("windspeedAvg", models.FloatField()),
                ("windspeedHigh", models.FloatField()),
                ("windspeedLow", models.FloatField()),
                ("etc", models.FloatField()),
                ("water_req", models.FloatField()),
            ],
        ),
    ]
