# Generated by Django 4.2.1 on 2023-05-23 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_wu", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weatherdata",
            name="solarRadiationHigh",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="weatherdata",
            name="uvHigh",
            field=models.FloatField(null=True),
        ),
    ]
